name: Update Site

on:
  push:
    branches: [ Java11 ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: PalladioSimulator/Palladio-Build-ActionsPipeline@07c634d900fa2a4979fe40764cb5e41ed05ea966
        with:
          deploy-updatesite: 'releng/org.palladiosimulator.pcm.confidentiality.context.updatesite/target/repository'
          server-ssh-key: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          remote-host: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
          remote-port: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
          remote-user: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
          remote-target: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
          skip-branch-deploy: false
          use-cache: false
